# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktg_detalle', models.CharField(max_length=15, verbose_name='Detalle')),
                ('ktg_abrevia', models.CharField(max_length=7, verbose_name='Abreviatura')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciu_nombres', models.CharField(max_length=25, verbose_name='Nombre')),
                ('ciu_abrevia', models.CharField(max_length=10, verbose_name='Abreviatura')),
            ],
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_detalle', models.CharField(max_length=20, verbose_name='Detalle')),
                ('mot_abrevia', models.CharField(max_length=10, verbose_name='Abreviatura')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pai_detalle', models.CharField(max_length=25, verbose_name='Nombre')),
                ('pai_abrevia', models.CharField(max_length=10, verbose_name='Abreviatura')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_detalle', models.CharField(max_length=25, verbose_name='Nombre')),
                ('est_abrevia', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('est_capital', models.CharField(max_length=30, verbose_name='Capital')),
                ('est_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suc_nombres', models.CharField(max_length=30, verbose_name='Nombre')),
                ('suc_abrevia', models.CharField(max_length=15, verbose_name='Abreviatura')),
                ('suc_direcci', models.CharField(max_length=45, verbose_name='Dirección')),
                ('suc_statreg', models.CharField(max_length=1, verbose_name='Status del Registro')),
                ('suc_ciudads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Ciudad')),
                ('suc_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Pais')),
                ('suc_estados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Tipomovim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmv_detalle', models.CharField(max_length=15, verbose_name='Detalle')),
                ('tmv_abrevia', models.CharField(max_length=10, verbose_name='Abreviatura')),
            ],
        ),
        migrations.CreateModel(
            name='Zipcodigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_idzipco', models.CharField(max_length=15, verbose_name='Código Postal')),
                ('zip_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Pais')),
                ('zip_estados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Provincia')),
                ('zip_idciuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='sucursal',
            name='suc_zipcodg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Zipcodigo'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='ciu_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Pais'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='ciu_estados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Provincia'),
        ),
    ]
