# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_auto_20171203_2105'),
        ('parametros', '0002_controlador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Motivo',
        ),
        migrations.DeleteModel(
            name='Tipomovim',
        ),
    ]
