# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_auto_20180114_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='suc_impuest',
            field=models.PositiveIntegerField(default=12, verbose_name='IVA/Impuesto %'),
        ),
    ]
