# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_sucursal_suc_impuest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='suc_codgsuc',
            field=models.PositiveIntegerField(null=True, verbose_name='Cód.Sucursal'),
        ),
        migrations.AlterField(
            model_name='controlador',
            name='ctl_secue01',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Secuencia 01 (Factura)'),
        ),
    ]
