# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def custom_function(apps, schema_editor):
        Sucursal = apps.get_model('parametros', 'Sucursal')
        sucursales = Sucursal.objects.all()
        for sucursal in sucursales:
            sucursal.suc_codgsuc = sucursal.id
            sucursal.save()

    dependencies = [
        ('parametros', '0004_auto_20180313_0042'),
    ]

    operations = [
        migrations.RunPython(custom_function, reverse_code=migrations.RunPython.noop),
    ]
