# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0005_auto_20180313_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='suc_codgsuc',
            field=models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Cód.Sucursal'),
        ),
    ]
