# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0006_auto_20180313_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlador',
            name='ctl_secue05',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Secuencia 05 Nota/Crédito'),
        ),
        migrations.AlterField(
            model_name='controlador',
            name='ctl_secue06',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Secuencia 06 Nota/Débito'),
        ),
    ]
