# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existencia',
            name='exs_tabtall',
            field=models.CharField(editable=False, max_length=5, null=True, verbose_name='Tabla de Tallas'),
        ),
    ]
