# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='col_abrevia',
            field=models.CharField(max_length=5, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='division',
            name='div_abrevia',
            field=models.CharField(max_length=7, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='mod_abrevia',
            field=models.CharField(max_length=8, verbose_name='Abreviatura'),
        ),
    ]
