# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productkey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pky_idcolor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.Color')),
                ('pky_iddivis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.Division')),
                ('pky_idmarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.Marca')),
                ('pky_idmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.Modelo')),
            ],
        ),
    ]
