# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
        ('inventarios', '0002_productkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='prd_tabtall',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='prd_tpoprod',
        ),
        migrations.AddField(
            model_name='existencia',
            name='exs_abrevia',
            field=models.CharField(default='A', max_length=25, verbose_name='Abreviatura  del Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existencia',
            name='exs_detalls',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15, verbose_name='Detallista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existencia',
            name='exs_imgprod',
            field=models.ImageField(default='', upload_to='productos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existencia',
            name='exs_statreg',
            field=models.BooleanField(default=True, verbose_name='Status del Registro'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='exs_tabtall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.Tabtalla'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='exs_tpoprod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventarios.Tipoproducto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existencia',
            name='pky_idcolor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventarios.Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existencia',
            name='pky_iddivis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventarios.Division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existencia',
            name='pky_idmarca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventarios.Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existencia',
            name='pky_idmodel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventarios.Modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existencia',
            name='pky_sucursa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametros.Sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productkey',
            name='pky_idsucur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametros.Sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_detalle',
            field=models.CharField(max_length=45, verbose_name='Detalle  del Producto'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_product',
            field=models.CharField(primary_key=False, db_index=True, editable=False, max_length=13, unique=True, verbose_name='Cód. Producto'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventarios.Existencia', verbose_name='Saldo x talla'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
