# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_auto_20171125_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existencia',
            name='exs_tabtall',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True, verbose_name='Tabla de Tallas'),
        ),
    ]
