# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_auto_20180315_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='col_abrevia',
            field=models.CharField(max_length=10, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_abrevia',
            field=models.CharField(editable=False, max_length=30, verbose_name='Abreviatura del Producto'),
        ),
    ]
