# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_auto_20171107_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productkey',
            name='pky_idcolor',
        ),
        migrations.RemoveField(
            model_name='productkey',
            name='pky_iddivis',
        ),
        migrations.RemoveField(
            model_name='productkey',
            name='pky_idmarca',
        ),
        migrations.RemoveField(
            model_name='productkey',
            name='pky_idmodel',
        ),
        migrations.RemoveField(
            model_name='productkey',
            name='pky_idsucur',
        ),
        migrations.RenameField(
            model_name='existencia',
            old_name='pky_idcolor',
            new_name='exs_idcolor',
        ),
        migrations.RenameField(
            model_name='existencia',
            old_name='pky_iddivis',
            new_name='exs_iddivis',
        ),
        migrations.RenameField(
            model_name='existencia',
            old_name='pky_idmarca',
            new_name='exs_idmarca',
        ),
        migrations.RenameField(
            model_name='existencia',
            old_name='pky_idmodel',
            new_name='exs_idmodel',
        ),
        migrations.RenameField(
            model_name='existencia',
            old_name='pky_sucursa',
            new_name='exs_sucursa',
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_abrevia',
            field=models.CharField(max_length=25, verbose_name='Abreviatura del Producto'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_detalle',
            field=models.CharField(editable=False, max_length=45, verbose_name='Detalle del Producto'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_imgprod',
            field=models.ImageField(blank=True, upload_to='productos'),
        ),
        migrations.DeleteModel(
            name='Productkey',
        ),
    ]
