# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_auto_20180315_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='tpo_idtipos',
            field=models.CharField(default='P', max_length=1, primary_key=True, serialize=False, verbose_name='Cód. Tipo/Producto'),
        ),
    ]
