# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_auto_20171109_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existencia',
            name='exs_abrevia',
            field=models.CharField(editable=False, max_length=25, verbose_name='Abreviatura del Producto'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_comprom',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, verbose_name='S.Compromet.(Ped. de Client)'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_cosprom',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, verbose_name='Costo promedio Actual'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_costact',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, verbose_name='Costo Actual'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_costant',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, verbose_name='Costo promedio Anterior'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_detalls',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, verbose_name='Detallista'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_dispant',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, verbose_name='Disponible Anterior'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_distrib',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, verbose_name='Distribuidor'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_egresos',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, verbose_name='Egresos'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_fechegr',
            field=models.DateTimeField(blank=True, verbose_name='Fecha Ult. Egreso'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_feching',
            field=models.DateTimeField(blank=True, verbose_name='Fecha de ult. Ingreso'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_fechinv',
            field=models.DateTimeField(blank=True, verbose_name='Fecha de inventario'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_ingreso',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, verbose_name='Ingresos'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_mayoris',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, verbose_name='Mayorista'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_publico',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, verbose_name='Publico'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_saldact',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, verbose_name='Saldo Actual'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_saldinc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, verbose_name='Saldo inicial'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_special',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, verbose_name='Especial'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_tabtall',
            field=models.CharField(default=1, editable=False, max_length=5, verbose_name='Tabla de Tallas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_xconfir',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, verbose_name='S. x confirm.(Ped.a Proveed)'),
        ),
    ]
