# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_auto_20171110_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_inici01',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. inici-01'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_inici02',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. inici-02'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_inici03',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. inici-03'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_inici04',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. inici-04'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_inici05',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. inici-05'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_inici06',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. inici-06'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_inici07',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. inici-07'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_inici08',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. inici-08'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_inici09',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. inici-09'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_inici10',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. inici-10'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_inici11',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. inici-11'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_inici12',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. inici-12'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_inici13',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. inici-13'),
        ),
    ]
