# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_auto_20171110_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_actua01',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. actua-01'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_actua02',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. actua-02'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_actua03',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. actua-03'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_actua04',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. actua-04'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_actua05',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. actua-05'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_actua06',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. actua-06'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_actua07',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. actua-07'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_actua08',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. actua-08'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_actua09',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. actua-09'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_actua10',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. actua-10'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_actua11',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. actua-11'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_actua12',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. actua-12'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_actua13',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. actua-13'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_compr01',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. compr-01'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_compr02',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. compr-02'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_compr03',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. compr-03'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_compr04',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. compr-04'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_compr05',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. compr-05'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_compr06',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. compr-06'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_compr07',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. compr-07'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_compr08',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. compr-08'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_compr09',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. compr-09'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_compr10',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. compr-10'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_compr11',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. compr-11'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_compr12',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. compr-12'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_compr13',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. compr-13'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_dispo01',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. dispo-01'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_dispo02',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. dispo-02'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_dispo03',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. dispo-03'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_dispo04',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. dispo-04'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_dispo05',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. dispo-05'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_dispo06',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. dispo-06'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_dispo07',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. dispo-07'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_dispo08',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. dispo-08'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_dispo09',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. dispo-09'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_dispo10',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. dispo-10'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_dispo11',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. dispo-11'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_dispo12',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. dispo-12'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_dispo13',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. dispo-13'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_egres01',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. egres-01'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_egres02',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. egres-02'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_egres03',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. egres-03'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_egres04',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. egres-04'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_egres05',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. egres-05'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_egres06',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. egres-06'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_egres07',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. egres-07'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_egres08',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. egres-08'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_egres09',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. egres-09'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_egres10',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. egres-10'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_egres11',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. egres-11'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_egres12',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. egres-12'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_egres13',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. egres-13'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_ingre01',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. ingre-01'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_ingre02',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. ingre-02'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_ingre03',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. ingre-03'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_ingre04',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. ingre-04'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_ingre05',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. ingre-05'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_ingre06',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. ingre-06'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_ingre07',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. ingre-07'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_ingre08',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. ingre-08'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_ingre09',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. ingre-09'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_ingre10',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. ingre-10'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_ingre11',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. ingre-11'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_ingre12',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. ingre-12'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_ingre13',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. ingre-13'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_xconf01',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. xconf-01'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_xconf02',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. xconf-02'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_xconf03',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. xconf-03'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_xconf04',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. xconf-04'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_xconf05',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. xconf-05'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_xconf06',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. xconf-06'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_xconf07',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. xconf-07'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_xconf08',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. xconf-08'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_xconf09',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. xconf-09'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_xconf10',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. xconf-10'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_xconf11',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. xconf-11'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_xconf12',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. xconf-12'),
        ),
        migrations.AlterField(
            model_name='saldoxtalla',
            name='tex_xconf13',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Cant. xconf-13'),
        ),
    ]
