# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0007_auto_20171110_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existencia',
            name='exs_fechegr',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Ult. Egreso'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_feching',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ult. Ingreso'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_fechinv',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inventario'),
        ),
    ]
