# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_auto_20171110_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existencia',
            name='exs_comprom',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='S.Compromet.(Ped. de Client)'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_cosprom',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Costo promedio Actual'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_costact',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Costo Actual'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_costant',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Costo promedio Anterior'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_detalls',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Detallista'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_dispant',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Disponible Anterior'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_distrib',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Distribuidor'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_egresos',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Egresos'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_ingreso',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Ingresos'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_mayoris',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Mayorista'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_publico',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Publico'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_saldact',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Saldo Actual'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_saldinc',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='Saldo inicial'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_special',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Especial'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='exs_xconfir',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, verbose_name='S. x confirm.(Ped.a Proveed)'),
        ),
    ]
