# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0010_auto_20171110_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existencia',
            name='exs_dsponib',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='Saldo disponible'),
        ),
    ]
