# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movicaja',
            name='mcj_motivos',
        ),
        migrations.AlterField(
            model_name='movicaja',
            name='mcj_tipomov',
            field=models.PositiveIntegerField(choices=[(1, 1), ('INGRESO', 'INGRESO'), ('Ingresos', 'Ingresos'), (2, 2), ('EGRESO', 'EGRESO'), ('Egresos', 'Egresos'), (3, 3), ('TRANSFER', 'TRANSFER'), ('Transferencias', 'Transferencias')], verbose_name='Tipo de movimiento'),
        ),
    ]
