# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-16 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movicaja',
            name='mcj_tipomov',
            field=models.PositiveIntegerField(choices=[(1, 'Ingresos'), (2, 'Egresos'), (3, 'Transferencias'), (5, 'Nota de crédito'), (6, 'Nota de débito')], verbose_name='Tipo de movimiento'),
        ),
    ]
