# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_auto_20171203_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movicaja',
            name='mcj_tipomov',
            field=models.PositiveIntegerField(choices=[(1, 'Ingresos'), (2, 'Egresos'), (3, 'Transferencias')], verbose_name='Tipo de movimiento'),
        ),
    ]
