# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('ing_ningres', models.AutoField(primary_key=True, serialize=False, verbose_name='Núm. de Ingreso')),
                ('ing_tipomov', models.PositiveIntegerField(choices=[(1, 'Ingresos'), (2, 'Egresos'), (3, 'Transferencias')], default=1, verbose_name='Tipo de movimiento')),
                ('ing_fechped', models.DateField(verbose_name='Fecha de pedido')),
                ('ing_statreg', models.CharField(default=1, max_length=1, verbose_name='Status del Registro')),
                ('ing_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.Proveedor')),
                ('ing_vendedo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='fac_ctrlfac',
            field=models.CharField(default='', editable=False, max_length=12, verbose_name='Núm. de Factura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_idfactu',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id. de Factura'),
        ),
    ]
