# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_sucursal_suc_impuest'),
        ('comercial', '0002_auto_20180114_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ped_sucursa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.Sucursal'),
        ),
    ]
