# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0006_auto_20180313_0054'),
        ('comercial', '0003_pedido_ped_sucursa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='ing_cliente',
            new_name='ing_proveed',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='ing_sucursa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.Sucursal'),
        ),
    ]
