# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_auto_20171115_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='ped_fechfac',
            new_name='ped_fechped',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='Ped_motivos',
            new_name='ped_motivos',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fac_pedidos',
        ),
        migrations.RemoveField(
            model_name='movinvent',
            name='mvi_factura',
        ),
        migrations.RemoveField(
            model_name='movinvent',
            name='mvi_pedidos',
        ),
        migrations.RemoveField(
            model_name='movinvent',
            name='mvi_sucursa',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped_cajanum',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped_cajeras',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped_mvinven',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped_totaran',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped_totdsct',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped_totflet',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped_totitms',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped_totrkrg',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped_tottaxs',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped_totvlor',
        ),
        migrations.AddField(
            model_name='factura',
            name='fac_npedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Pedido', verbose_name='Núm. de Pedido'),
        ),
        migrations.AddField(
            model_name='movinvent',
            name='mvi_npedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Pedido', verbose_name='Núm. de pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ped_npedido',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Núm. de Pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_cajanum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.Caja', verbose_name='Núm. de caja'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_cajeras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.Cajera', verbose_name='Cód. de Cajera'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Cliente', verbose_name='Cód. de Cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_cotizac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Cotización'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_monedas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.Moneda', verbose_name='Núm. de Moneda'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_otropgo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Internet (Paypal)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_pgocheq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cheque'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_pgocred',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Crédito personal'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_pgoefec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cash'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_pgotjcr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='T./Crédito'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_totaran',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total aranceles'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_totdsct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total de descuentos'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_totflet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total por deliver (transporte)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_totitms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total de items'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_totrkrg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total de recaregos'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_tottaxs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total taxes'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_totvlor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total del valor'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fac_vendedo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Vendedor', verbose_name='Cód. de Vendedor'),
        ),
        migrations.AlterField(
            model_name='movinvent',
            name='mvi_arancel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Aranceles'),
        ),
        migrations.AlterField(
            model_name='movinvent',
            name='mvi_deliver',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Transporte'),
        ),
        migrations.AlterField(
            model_name='movinvent',
            name='mvi_desctos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Descuentos'),
        ),
        migrations.AlterField(
            model_name='movinvent',
            name='mvi_impuest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Impuestos IVA.'),
        ),
        migrations.AlterField(
            model_name='movinvent',
            name='mvi_kntidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Cantidad Total'),
        ),
        migrations.AlterField(
            model_name='movinvent',
            name='mvi_precios',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='movinvent',
            name='mvi_rcargos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Recargos'),
        ),
        migrations.AlterField(
            model_name='movinvent',
            name='mvi_tipomov',
            field=models.CharField(max_length=1, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='movinvent',
            name='mvi_unidade',
            field=models.CharField(max_length=5, verbose_name='Unidad'),
        ),
    ]
