# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_auto_20180402_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='ing_fechped',
            field=models.DateField(verbose_name='Fecha de compra'),
        ),
    ]
