# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_auto_20171125_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ped_statreg',
            field=models.CharField(default='1', max_length=1, verbose_name='Status del Registro'),
        ),
    ]
