# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_movinvent_mvi_nummovi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='clt_celular',
            field=models.CharField(blank=True, max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clt_imgclte',
            field=models.ImageField(blank=True, upload_to='clientes'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clt_rgunico',
            field=models.CharField(blank=True, max_length=20, verbose_name='Registro Unico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clt_telefon',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='movinvent',
            name='mvi_factura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Núm. de factura'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prv_imgprov',
            field=models.ImageField(blank=True, upload_to='proveedores'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prv_rgunico',
            field=models.CharField(blank=True, max_length=20, verbose_name='Registro Unico'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vnd_addrimg',
            field=models.ImageField(blank=True, upload_to='vendedores'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vnd_ncelula',
            field=models.CharField(blank=True, max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vnd_rgunico',
            field=models.CharField(blank=True, max_length=20, verbose_name='Registro Unico'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vnd_telefon',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefono'),
        ),
    ]
