# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_pedido_ped_statreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movinvent',
            name='mvi_motivos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped_motivos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='ped_tipomov',
            field=models.PositiveIntegerField(choices=[(1, 'Ingresos'), (2, 'Egresos'), (3, 'Transferencias')], default=2, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='movinvent',
            name='mvi_tipomov',
            field=models.PositiveIntegerField(choices=[(1, 'Ingresos'), (2, 'Egresos'), (3, 'Transferencias')], verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ped_statreg',
            field=models.CharField(default=1, max_length=1, verbose_name='Status del Registro'),
        ),
    ]
