# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_auto_20180408_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='movinvent',
            name='mvi_ningres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Ingreso', verbose_name='Núm. de ingreso'),
        ),
    ]
