# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_movinvent_mvi_ningres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movinvent',
            name='mvi_proveed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Proveedor'),
        ),
        migrations.AlterField(
            model_name='movinvent',
            name='mvi_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Cliente'),
        ),
    ]
