# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('comercial', '0008_auto_20180408_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('com_idcompr', models.AutoField(primary_key=True, serialize=False, verbose_name='Id. de Compra')),
                ('com_facprov', models.CharField(max_length=12, verbose_name='Nº Fac. Proveedor')),
                ('com_fechcom', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la Compra')),
                ('com_cotizac', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Cotización')),
                ('com_totitms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total de items')),
                ('com_totvlor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total del valor')),
                ('com_totdsct', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total de descuentos')),
                ('com_totrkrg', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total de recaregos')),
                ('com_totflet', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total por deliver (transporte)')),
                ('com_totaran', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total aranceles')),
                ('com_tottaxs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total taxes')),
                ('com_pgoefec', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cash')),
                ('com_pgocheq', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cheque')),
                ('com_pgotjcr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='T./Crédito')),
                ('com_pgocred', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Crédito personal')),
                ('com_otropgo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Internet (Paypal)')),
                ('com_cajanum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.Caja', verbose_name='Núm. de caja')),
                ('com_cajeras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.Cajera', verbose_name='Cód. de Cajera')),
                ('com_monedas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.Moneda', verbose_name='Núm. de Moneda')),
                ('com_ningres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Ingreso', verbose_name='Núm. de Ingreso')),
                ('com_proveed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Proveedor', verbose_name='Cód. de Proveedor')),
                ('com_vendedo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Vendedor', verbose_name='Cód. de Vendedor')),
            ],
        ),
    ]
