# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_ingreso_ing_facprov'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cli_country',
            new_name='clt_country',
        ),
    ]
