# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('parametros', '0007_auto_20180427_2305'),
        ('comercial', '0011_auto_20180420_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajustecr',
            fields=[
                ('ajc_najustc', models.AutoField(primary_key=True, serialize=False, verbose_name='Núm. de Nota/cr')),
                ('ajc_tipomov', models.PositiveIntegerField(choices=[(1, 'Ingresos'), (2, 'Egresos'), (3, 'Transferencias')], default=2, verbose_name='Tipo de movimiento')),
                ('ajc_fechajs', models.DateField(verbose_name='Fecha de Nota/cr')),
                ('ajc_facclte', models.CharField(max_length=15, verbose_name='Nº Fac. Cliente')),
                ('ajc_statreg', models.CharField(default=1, max_length=1, verbose_name='Status del Registro')),
                ('ajc_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.Cliente')),
                ('ajc_sucursa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.Sucursal')),
                ('ajc_vendedo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Ajustedb',
            fields=[
                ('ajd_najustd', models.AutoField(primary_key=True, serialize=False, verbose_name='Núm. de Nota/db')),
                ('ajd_tipomov', models.PositiveIntegerField(choices=[(1, 'Ingresos'), (2, 'Egresos'), (3, 'Transferencias')], default=2, verbose_name='Tipo de movimiento')),
                ('ajd_fechajs', models.DateField(verbose_name='Fecha de Nota/db')),
                ('ajd_facprov', models.CharField(max_length=15, verbose_name='Nº Fac. Proveedor')),
                ('ajd_statreg', models.CharField(default=1, max_length=1, verbose_name='Status del Registro')),
                ('ajd_proveed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.Proveedor')),
                ('ajd_sucursa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.Sucursal')),
                ('ajd_vendedo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Notacred',
            fields=[
                ('ncr_idnotas', models.AutoField(primary_key=True, serialize=False, verbose_name='Id. de Notacred')),
                ('ncr_ctrlnta', models.CharField(editable=False, max_length=12, verbose_name='Núm. de Notacred')),
                ('ncr_fechnta', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la Notacred')),
                ('ncr_cotizac', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Cotización')),
                ('ncr_totitms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total de items')),
                ('ncr_totvlor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total del valor')),
                ('ncr_totdsct', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total de descuentos')),
                ('ncr_totrkrg', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total de recaregos')),
                ('ncr_totflet', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total por deliver (transporte)')),
                ('ncr_totaran', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total aranceles')),
                ('ncr_tottaxs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total taxes')),
                ('ncr_pgoefec', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cash')),
                ('ncr_pgocheq', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cheque')),
                ('ncr_pgotjcr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='T./Crédito')),
                ('ncr_pgocred', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Crédito personal')),
                ('ncr_otropgo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Internet (Paypal)')),
                ('ncr_cajanum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.Caja', verbose_name='Núm. de caja')),
                ('ncr_cajeras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.Cajera', verbose_name='Cód. de Cajera')),
                ('ncr_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Cliente', verbose_name='Cód. de Cliente')),
                ('ncr_monedas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.Moneda', verbose_name='Núm. de Moneda')),
                ('ncr_najuste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Ajustecr', verbose_name='Núm. de ajuste')),
                ('ncr_vendedo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Vendedor', verbose_name='Cód. de Vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='movinvent',
            name='mvi_najustc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Ajustecr', verbose_name='Núm. de Ajuste/cr.'),
        ),
        migrations.AddField(
            model_name='movinvent',
            name='mvi_najustd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.Ajustedb', verbose_name='Núm. de Ajuste/db.'),
        ),
    ]
