# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-16 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_auto_20180427_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustecr',
            name='ajc_tipomov',
            field=models.PositiveIntegerField(choices=[(1, 'Ingresos'), (2, 'Egresos'), (3, 'Transferencias'), (5, 'Nota de crédito'), (6, 'Nota de débito')], default=5, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='ajustedb',
            name='ajd_tipomov',
            field=models.PositiveIntegerField(choices=[(1, 'Ingresos'), (2, 'Egresos'), (3, 'Transferencias'), (5, 'Nota de crédito'), (6, 'Nota de débito')], default=6, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='ing_tipomov',
            field=models.PositiveIntegerField(choices=[(1, 'Ingresos'), (2, 'Egresos'), (3, 'Transferencias'), (5, 'Nota de crédito'), (6, 'Nota de débito')], default=1, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='movinvent',
            name='mvi_tipomov',
            field=models.PositiveIntegerField(choices=[(1, 'Ingresos'), (2, 'Egresos'), (3, 'Transferencias'), (5, 'Nota de crédito'), (6, 'Nota de débito')], verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ped_tipomov',
            field=models.PositiveIntegerField(choices=[(1, 'Ingresos'), (2, 'Egresos'), (3, 'Transferencias'), (5, 'Nota de crédito'), (6, 'Nota de débito')], default=2, verbose_name='Tipo de movimiento'),
        ),
    ]
